apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: xuerong/kub-demo-frontend:latest
          env:
            - name: TASK_ADDRESS
              value: "tasks-service.default" #coreDNS: servicename.namespace