apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  # type: ClusterIp  // default use for internal loadbalance
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
