FROM ubuntu:22.04

ARG USER=ubuntu
ARG PASSWD=adminAb1
RUN apt update && apt install  openssh-server sudo curl vim git zsh -y
RUN useradd -rm -d /home/${USER} -s /usr/bin/zsh -g root -G sudo -u 1000 ${USER}
RUN echo "${USER}:${PASSWD}" | chpasswd

USER ubuntu
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN mkdir ~/Application
RUN mkdir ~/Downloads
RUN touch ~/.application.sh
RUN echo "source ~/.application.sh" >> ~/.zshrc

ARG JDK_VERSION=jdk-21
ARG JDK_HASH=7c1f7689db0f4b48ee6978029c4a1aecd1442a8a7637cdf43a5471d0c79712a8
ARG JDK_URL=https://download.oracle.com/java/21/latest/${JDK_VERSION}_linux-x64_bin.tar.gz
RUN curl -o ~/Downloads/${JDK_VERSION}.tar.gz ${JDK_URL}
# RUN echo "${JDK_HASH} ~/Downloads/${JDK_VERSION}.tar.gz" | sha256sum -c
RUN mkdir -p ~/Application/${JDK_VERSION}
RUN tar -zxf ~/Downloads/${JDK_VERSION}.tar.gz -C ~/Application/${JDK_VERSION} --strip-components=1
# escape=`
RUN echo "export JAVA_HOME=\$HOME/Application/${JDK_VERSION}" >> ~/.application.sh
RUN echo "export PATH=\$JAVA_HOME/bin\${PATH:+:\${PATH}}" >> ~/.application.sh

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

# ssh admin@localhost -p 4022
# TODO: find why to install oh-my-zsh