FROM ubuntu:22.04

RUN apt update && apt install  openssh-server sudo curl vim git zsh -y
RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1000 admin 
RUN  echo 'admin:adminAb1' | chpasswd
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

# ssh admin@localhost -p 4022 
# TODO: find why to install oh-my-zsh