FROM ubuntu:22.04

ARG USER=ubuntu
ARG PASSWD=adminAb1
RUN apt update && apt install  openssh-server sudo curl vim git zsh unzip gpg -y
RUN useradd -rm -d /home/${USER} -s /usr/bin/zsh -g root -G sudo -u 1000 ${USER}
RUN echo "${USER}:${PASSWD}" | chpasswd
# Nano use
RUN chmod 777 /opt/

USER ubuntu
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN mkdir ~/Application
RUN mkdir ~/Downloads
RUN touch ~/.application.sh
RUN echo "source ~/.application.sh" >> ~/.zshrc

# JAVA Install
ARG JDK_VERSION=21
ARG JDK_URL=https://download.oracle.com/java/21/latest/jdk-${JDK_VERSION}_linux-x64_bin.tar.gz
ARG JDK_SHA_256=7c1f7689db0f4b48ee6978029c4a1aecd1442a8a7637cdf43a5471d0c79712a8


ARG JDK_NAME=jdk_${JDK_VERSION}
RUN curl -o ~/Downloads/${JDK_NAME}.tar.gz ${JDK_URL}
# escape=`
RUN echo "${JDK_SHA_256} ${HOME}/Downloads/${JDK_NAME}.tar.gz" | sha256sum -c
RUN mkdir -p ~/Application/${JDK_NAME}
RUN tar -zxf ~/Downloads/${JDK_NAME}.tar.gz -C ~/Application/${JDK_NAME} --strip-components=1
RUN echo "export JAVA_HOME=\$HOME/Application/${JDK_NAME}" >> ~/.application.sh
RUN echo "export PATH=\$JAVA_HOME/bin\${PATH:+:\${PATH}}" >> ~/.application.sh

# Node Install
ARG NODE_VERSION=v20.9.0
ARG NODE_URL=https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz
ARG NODE_SHA_256=f0919f092fbf74544438907fa083c21e76b2d7a4bc287f0607ada1553ef16f60

ARG NODE_NAME=node_${NODE_VERSION}
RUN curl -o ~/Downloads/${NODE_NAME}.tar.gz ${NODE_URL}
RUN echo "${NODE_SHA_256} ${HOME}/Downloads/${NODE_NAME}.tar.gz" | sha256sum -c
RUN mkdir -p ~/Application/${NODE_NAME}
RUN tar -zxf ~/Downloads/${NODE_NAME}.tar.gz -C ~/Application/${NODE_NAME} --strip-components=1
RUN echo "export NODE_HOME=\$HOME/Application/${NODE_NAME}" >> ~/.application.sh
RUN echo "export PATH=\$NODE_HOME/bin\${PATH:+:\${PATH}}" >> ~/.application.sh

# Gradle Install
ARG GRADLE_VERSION=8.4
ARG GRADLE_URL=https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip
ARG GRADLE_SHA_256=f2b9ed0faf8472cbe469255ae6c86eddb77076c75191741b4a462f33128dd419

ARG GRADLE_NAME=gradle-${GRADLE_VERSION}
RUN curl --location -o ~/Downloads/${GRADLE_NAME}.zip ${GRADLE_URL}
RUN echo "${GRADLE_SHA_256} ${HOME}/Downloads/${GRADLE_NAME}.zip" | sha256sum -c
RUN mkdir -p ~/Application/${GRADLE_NAME}
RUN rm -rf ~/Downloads/.tmp/ \
    && mkdir ~/Downloads/.tmp/ \
    && unzip -qq -d ~/Downloads/.tmp/ ~/Downloads/gradle-${GRADLE_VERSION}.zip \
    && mv ~/Downloads/.tmp/*/* ~/Application/${GRADLE_NAME} \
    && rm -rf ~/Download/.tmp/
RUN echo "export GRADLE_HOME=\$HOME/Application/${GRADLE_NAME}" >> ~/.application.sh
RUN echo "export PATH=\$GRADLE_HOME/bin\${PATH:+:\${PATH}}" >> ~/.application.sh

# Maven Install
ARG MAVEN_VERSION=3.9.5
ARG MAVEN_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz

ARG MAVEN_NAME=maven_${MAVEN_VERSION}
ARG MAVEN_SHA_512=4810523ba025104106567d8a15a8aa19db35068c8c8be19e30b219a1d7e83bcab96124bf86dc424b1cd3c5edba25d69ec0b31751c136f88975d15406cab3842b
RUN curl -o ~/Downloads/${MAVEN_NAME}.tar.gz ${MAVEN_URL}
RUN echo "${MAVEN_SHA_512} ${HOME}/Downloads/${MAVEN_NAME}.tar.gz" | sha512sum -c
RUN mkdir -p ~/Application/${MAVEN_NAME}
RUN tar -zxf ~/Downloads/${MAVEN_NAME}.tar.gz -C ~/Application/${MAVEN_NAME} --strip-components=1
RUN echo "export NODE_HOME=\$HOME/Application/${MAVEN_NAME}" >> ~/.application.sh
RUN echo "export PATH=\$NODE_HOME/bin\${PATH:+:\${PATH}}" >> ~/.application.sh

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

# docker build -t xrw/ubuntu:me .
# docker run -p 4022:22 -d --name ubuntu xrw/ubuntu:me
# ssh admin@localhost -p 4022